export * from './language.interface.js'
export * from './slide.interface.js'
export * from './slideTranslation.interface.js'
export * from './user.interface.js'
export * from './logo.interface.js'
export * from './infor.interface.js'
export * from './attendance.interface.js'
export * from './project.interface.js'
