export * from './language.interface'
export * from './slide.interface'
export * from './slideTranslation.interface'
export * from './user.interface'
export * from './logo.interface'
export * from './infor.interface'
export * from './attendance.interface'
export * from './project.interface'
