/* export * from './language.controller'
export * from './auth.controller'
export * from './slide.controller'
export * from './logo.controler'
export * from './user.controller'
export * from './infor.controller'
export * from './project.controller'
export * from './attendance.controller'
export * from './quotation.controller'
export * from './progressEntry.controller'
export * from './projectType.controller'
export * from './productCategory.controller'
export * from './productBrand.controller'
export * from './product.controller'
export * from './inforCompanny.controller'
export * from './quote.controller'
export * from './installation.controller'
export * from './page.controller'
export * from './order.controller'
 */
